version: 0.5.1.{build}

branches:
  # whitelist
  only:
    - master
    - develop

# Do not build on tags (GitHub only)
skip_tags: true

# Operating system (build VM template)
os: Windows Server 2012

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: false

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true

platform: Any CPU
configuration: Debug

build:
  project: WitSync.sln
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  # MSBuild verbosity level
  verbosity: minimal

# scripts to run before build
before_build:
  - nuget restore
  
artifacts:
  # pushing all *.nupkg files in directory
  - path: witsync.*.nupkg

test: off

deploy:
  provider: NuGet
  server: https://ci.appveyor.com/nuget/witsync-8n5g4bnxalj3 # private appveyor feed
  api_key:
    secure: aIeIJNJAv5miMuzkKyGcSR6gsDB/c7WH2SN8PQkscBw=
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /witsync\..*\.nupkg/
