# manually align with Version.properties
version: 0.7.{build}-beta

branches:
  # whitelist
  only:
    - master
    - develop

# Do not build on tags (GitHub only)
skip_tags: true

# disable patching of AssemblyInfo.* files
assembly_info:
  patch: false

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true

platform: Any CPU
configuration: Debug    # beta mode

build:
  project: WitSync.sln
  publish_nuget: false            # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false    # generate and publish NuGet symbol packages
  # MSBuild verbosity level
  verbosity: minimal

# scripts to run before build
before_build:
  - nuget restore

# scripts to run after build
after_build:
  - nuget pack build\WitSync.nuspec -Prop Configuration=%CONFIGURATION% -NoPackageAnalysis
  - appveyor PushArtifact witsync.*.nupkg

# cannot run integration tests in AppVeyor
test: off
